app: url-shortener
name: url-shortener-express
component: express
org: gjgdserverless

inputs:
  src: ./
  domain: tiny.gjgd.xyz
  env:
    DYNAMODB_TABLE: ${output:url-shortener-db.name}
    URL: tiny.gjgd.xyz
