app: url-shortener
name: url-shortener-express
component: express
org: gjgdserverless
stage: dev

inputs:
  src:
    hook: npm run build
    dist: ../../dist
  domain: dev-tiny.gjgd.xyz
  env:
    DYNAMODB_TABLE: ${output:url-shortener-db.name}
    SECRET_UUID_NAMESPACE: ${env:SECRET_UUID_NAMESPACE}
