app: url-shortener
name: url-shortener-db
component: aws-dynamodb
org: gjgdserverless
stage: prod

inputs:
  name: ${name}-${stage}
  region: us-east-1
  # Prevent the Database Table from being removed when "serverless remove" is run
  deletionPolicy: retain
  attributeDefinitions:
    - AttributeName: id
      AttributeType: S
  keySchema:
    - AttributeName: id
      KeyType: HASH
