name: Deploy to AWS

on:
  push:
    branches:
      - main
      - update-readme

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm install

    - name: Serverless deploy app
      run: npm i -g serverless && npm run deploy:prod
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
